FROM python:3.10-slim

WORKDIR /usr/src/app/src

COPY src/WitiBotFiles/requirements.txt /usr/src/app/src
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /usr/src/app
COPY src/witi_bot.py /usr/src/app/src
COPY src/botBase /usr/src/app/src/botBase