services:
  mensabot:
    build:
      context: .
      dockerfile: Dockerfile.mensabot
    ports:
      - "80:80"
    secrets:
      - op_service_account_token
    volumes:
      - ./src/WitiGrailleBotFiles:/usr/src/app/src/WitiGrailleBotFiles
    environment:
      - NAME=MensaBot
    command: [ "python", "./mensa_bot.py" ]

  witibot:
    build:
      context: .
      dockerfile: Dockerfile.witibot
    ports:
      - "443:443"
    secrets:
      - op_service_account_token
    volumes:
      - ./src/WitiBotFiles:/usr/src/app/src/WitiBotFiles
    environment:
      - NAME=WitiBot
    command: [ "python", "./witi_bot.py" ]

secrets:
  op_service_account_token:
    file: ./op_service_account_token.txt
