name: witi
channels:
  - conda-forge
dependencies:
  - pip
  - python=3.10
  - pip:
      - numpy
      - python-telegram-bot==20.0a2
      - transformers
      - sentencepiece
      - torch
      - tensorflow
      - "jax[cpu]"
      - protobuf==3.20.*
      - pyMensa
      
